name: HW4 continuous integration

on:
  push:
    branches:
      - 'hw4'
    
jobs:
  test_complex:
    name: test implementation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: install dependency
        run: pip install pytest
      - name: run test suite
        run: python -m pytest ./homework/hw4/submission
