name: HW4 Continuous Integration

on:
  push:
    branches: 
     - 'hw4'

jobs:
    my_first_ci_job:
        runs-on: ubuntu-latest
        steps:
            - run: date
            - run: hostname

    test_complex:
        name: Test Python implementation of complex numbers
        runs-on: ubuntu-latest
        steps:
            # Checkout the head of branch `hw4` (what you just pushed)
            # See: https://github.com/actions/checkout
            - uses: actions/checkout@v3
            # Setup Python environment in the container
            # See: https://github.com/actions/setup-python
            - uses: actions/setup-python@v3
            with:
                python-version: '3.10' # let's use a recent version
            - name: Install Python dependencies
            run: pip install pytest
            - name: Run complex number test suite
            run: ~/classes/CS107/git/myrepo/homework/hw4/submission
